app/urls.py
from django.urls import path
from . import views

app_name = 'app'

user = [
    path('sign-up/', views.UserSignUpView.as_view(), name='sign-up'),
    path('sign-in/', views.UserSignInView.as_view(), name='sign-in'),
    path('sign-out/', views.UserSignOutView.as_view(), name='sign-out'),
    path('user/<int:pk>/update', views.UserUpdateView.as_view(), name='user-update-view'),
    path('search/user/', views.SearchResultsUserListView.as_view(), name='search-results-user-list-view'),
]

user_profile = [
    path('profile/<slug:slug>/', views.UserProfileDetailView.as_view(), name='profile-detail-view'),
]

post = [
    path('for-you/', views.ForYouPostListView.as_view(), name='for-you-post-list-view'),
    path('following/', views.FollowingPostListView.as_view(), name='following-post-list-view'),
    path('post/<slug:slug>/', views.PostDetailView.as_view(), name='post-detail-view'),
    path('post/create', views.PostCreateView.as_view(), name='post-create-view'),
    path('post/<slug:slug>/update', views.PostUpdateView.as_view(), name='post-update-view'),
    path('post/<slug:slug>/delete', views.PostDeleteView.as_view(), name='post-delete-view'),
]

tag = [
    path('tag/<slug:slug>/', views.TagDetailView.as_view(), name='tag-detail-view'),
]

urlpatterns = [
    path('', views.IndexTemplateView.as_view(), name='index-template-view'),
    *user,
    *user_profile,
    *post,
    *tag
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/templates/app/includes/layout/modals/modal_context/_modal_context.html
{% load static %}
<button type="button" class="button button--small button--invisible" data-modal-actions-target="#modal-context-for-post-{{ post.id }}">
    <svg class="icon icon-24">
        <use xlink:href="{% static 'app/assets/icons/sprite.svg' %}#icon-dots-vertical-rounded"></use>
    </svg>
</button>

<div class="modal-context" id="modal-context-for-post-{{ post.id }}">

    <ul class="modal-context__list">

        <li class="modal-context__item">
            <a href="{% url 'app:post-update-view' slug=post.slug %}" class="link link--small">
                <svg class="icon icon-24">
                    <use xlink:href="{% static 'app/assets/icons/sprite.svg' %}#icon-edit"></use>
                </svg>
                <span>Update</span>
            </a>
        </li>

        <li class="modal-context__item">
            <form action="{% url 'app:post-delete-view' slug=post.slug %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="button button--small button--invisible-danger">
                    <svg class="icon icon-24">
                        <use xlink:href="{% static 'app/assets/icons/sprite.svg' %}#icon-trash"></use>
                    </svg>
                    <span>Delete</span>
                </form>
            </button>
        </li>

    </ul>

</div>